apiVersion: apps/v1
kind: Deployment
metadata:
  name: meli-dnaanalyzer-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: meli-dnaanalyzer-api
  template:
    metadata:
      labels:
        app: meli-dnaanalyzer-api
    spec:
      containers:
      - name: meli-dnaanalyzer-api
        image: melitest.azurecr.io/meli-dnaanalyzer-api:c2c5221d9a0e40ec2b5d184ce364fb8ac0bfcb22
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          timeoutSeconds: 5
          initialDelaySeconds: 90
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 600Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: xxx