apiVersion: apps/v1
kind: Deployment
metadata:
  name: meli-dnaanalyzer-api
spec:
  replicas: 20
  selector:
    matchLabels:
      app: meli-dnaanalyzer-api
  template:
    metadata:
      labels:
        app: meli-dnaanalyzer-api
    spec:
      containers:
      - name: meli-dnaanalyzer-api
        image: melitest.azurecr.io/meli-dnaanalyzer-api:c2c5221d9a0e40ec2b5d184ce364fb8ac0bfcb22
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /liveness
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: xxx